{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "defe5511-3acc-439f-934b-6dc9f55a8cc3",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "8f8aa612-fc4a-4c14-8222-21c1cbe8025a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "  Hospital ID       Hospital Name Hospital Type       City        State  \\\n",
      "0   HOSP00016        C K Hospital       Private     Mumbai  Maharashtra   \n",
      "1   HOSP00019  Cure Well Hospital       Private  Bengaluru    Karnataka   \n",
      "2   HOSP00004    Yashoda Hospital       Private  Hyderabad    Telangana   \n",
      "3   HOSP00017     Dharma Hospital       Private      Delhi        Delhi   \n",
      "4   HOSP00017     Dharma Hospital       Private      Delhi        Delhi   \n",
      "\n",
      "         Department Department ID            Doctor  Nurses  Staff Count  ...  \\\n",
      "0  General Medicine       DEPT004  Dr. Arjun Sharma      12          257  ...   \n",
      "1   General Surgery       DEPT010     Dr. Sneha Rao      15          288  ...   \n",
      "2       Pulmonology       DEPT005   Dr. Priya Reddy      20          181  ...   \n",
      "3       Pulmonology       DEPT005   Dr. Rahul Verma      23          170  ...   \n",
      "4               ICU       DEPT009   Dr. Priya Reddy      34          116  ...   \n",
      "\n",
      "  Beds Available ICU Beds Bed Number  Bed Occupied         Equipment  \\\n",
      "0             70       79         35            No   Patient Monitor   \n",
      "1            219       41        306           Yes   Patient Monitor   \n",
      "2             45       23        159            No  Dialysis Machine   \n",
      "3            160       67        380           Yes  Dialysis Machine   \n",
      "4            409       39          1            No   Patient Monitor   \n",
      "\n",
      "  Length of Stay Room No Billing Amount Insurance Provider Readmission  \n",
      "0             14     458         473156      ICICI Lombard          No  \n",
      "1              4     657         488940      ICICI Lombard          No  \n",
      "2              4     943         414622          Niva Bupa          No  \n",
      "3             11     615         298345      ICICI Lombard          No  \n",
      "4              3     783         307428        Star Health          No  \n",
      "\n",
      "[5 rows x 32 columns]\n",
      "   Equipment Usage Duration Patient Analysis Patient Movement  \\\n",
      "0                      52.6        Recovered               No   \n",
      "1                      26.1        Recovered              Yes   \n",
      "2                       5.0        Recovered               No   \n",
      "3                      34.3        Recovered               No   \n",
      "4                       2.3        Recovered               No   \n",
      "\n",
      "  Patient Transfer to Another Department  Current Department Duration  \\\n",
      "0                            No Transfer                           48   \n",
      "1              Pulmonology -> Cardiology                           48   \n",
      "2                            No Transfer                          360   \n",
      "3                            No Transfer                           96   \n",
      "4                            No Transfer                           48   \n",
      "\n",
      "  Doctor In Charge  \n",
      "0          DOC0350  \n",
      "1          DOC0009  \n",
      "2          DOC0244  \n",
      "3          DOC0096  \n",
      "4          DOC0168  \n"
     ]
    }
   ],
   "source": [
    "df1 = pd.read_excel(\"Hospital_Dataset.xlsx\")\n",
    "df2 = pd.read_excel(\"Patient_Dataset.xlsx\")\n",
    "\n",
    "print(df1.head())\n",
    "print(df2.head())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "0c0b9e75-85fb-4dd7-9355-b948b07bfac2",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Index(['Hospital ID', 'Hospital Name', 'Hospital Type', 'City', 'State',\n",
      "       'Department', 'Department ID', 'Doctor', 'Nurses', 'Staff Count',\n",
      "       'Patient ID', 'Patient Name', 'Gender', 'Age', 'Admission Date',\n",
      "       'Discharge Date', 'Diagnosis', 'Treatment', 'Medication',\n",
      "       'Admission Type', 'Test Result', 'Blood Type', 'Beds Available',\n",
      "       'ICU Beds', 'Bed Number', 'Bed Occupied', 'Equipment', 'Length of Stay',\n",
      "       'Room No', 'Billing Amount', 'Insurance Provider', 'Readmission'],\n",
      "      dtype='str')\n",
      "Index(['Equipment Usage Duration', 'Patient Analysis', 'Patient Movement',\n",
      "       'Patient Transfer to Another Department', 'Current Department Duration',\n",
      "       'Doctor In Charge'],\n",
      "      dtype='str')\n"
     ]
    }
   ],
   "source": [
    "print(df1.columns)\n",
    "print(df2.columns)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "6feecaf4-3f2d-48b4-99d8-83a15257f0ff",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Index([], dtype='str')\n"
     ]
    }
   ],
   "source": [
    "same_columns = df1.columns.intersection(df2.columns)\n",
    "print(same_columns)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "c4b416b0-449c-47f7-b570-0b4574cf24f5",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "  Hospital ID       Hospital Name Hospital Type       City        State  \\\n",
      "0   HOSP00016        C K Hospital       Private     Mumbai  Maharashtra   \n",
      "1   HOSP00019  Cure Well Hospital       Private  Bengaluru    Karnataka   \n",
      "2   HOSP00004    Yashoda Hospital       Private  Hyderabad    Telangana   \n",
      "3   HOSP00017     Dharma Hospital       Private      Delhi        Delhi   \n",
      "4   HOSP00017     Dharma Hospital       Private      Delhi        Delhi   \n",
      "\n",
      "         Department Department ID            Doctor  Nurses  Staff Count  ...  \\\n",
      "0  General Medicine       DEPT004  Dr. Arjun Sharma      12          257  ...   \n",
      "1   General Surgery       DEPT010     Dr. Sneha Rao      15          288  ...   \n",
      "2       Pulmonology       DEPT005   Dr. Priya Reddy      20          181  ...   \n",
      "3       Pulmonology       DEPT005   Dr. Rahul Verma      23          170  ...   \n",
      "4               ICU       DEPT009   Dr. Priya Reddy      34          116  ...   \n",
      "\n",
      "  Room No Billing Amount Insurance Provider  Readmission  \\\n",
      "0     458         473156      ICICI Lombard           No   \n",
      "1     657         488940      ICICI Lombard           No   \n",
      "2     943         414622          Niva Bupa           No   \n",
      "3     615         298345      ICICI Lombard           No   \n",
      "4     783         307428        Star Health           No   \n",
      "\n",
      "  Equipment Usage Duration Patient Analysis Patient Movement  \\\n",
      "0                     52.6        Recovered               No   \n",
      "1                     26.1        Recovered              Yes   \n",
      "2                      5.0        Recovered               No   \n",
      "3                     34.3        Recovered               No   \n",
      "4                      2.3        Recovered               No   \n",
      "\n",
      "  Patient Transfer to Another Department Current Department Duration  \\\n",
      "0                            No Transfer                        48.0   \n",
      "1              Pulmonology -> Cardiology                        48.0   \n",
      "2                            No Transfer                       360.0   \n",
      "3                            No Transfer                        96.0   \n",
      "4                            No Transfer                        48.0   \n",
      "\n",
      "  Doctor In Charge  \n",
      "0          DOC0350  \n",
      "1          DOC0009  \n",
      "2          DOC0244  \n",
      "3          DOC0096  \n",
      "4          DOC0168  \n",
      "\n",
      "[5 rows x 38 columns]\n"
     ]
    }
   ],
   "source": [
    "merge_files = pd.concat([df1, df2], axis=1)\n",
    "\n",
    "print(merge_files.head())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "7f81319b-8ef6-4e5a-bb3e-1e0ee63b13f4",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Successfully Saved!\n"
     ]
    }
   ],
   "source": [
    "merge_files.to_csv(\"Final_Hospital_Dataset.csv\", index=False)\n",
    "print(\"Successfully Saved!\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "20f539ab-96fc-49e3-812d-dc0d5b79a457",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "e105e80a",
   "metadata": {},
   "source": [
    "## Cleaning Notebook\n",
    "This notebook creates a reproducible data-cleaning script `clean_hospital_data.py`, runs the cleaning pipeline on `hospital_cleaned.csv`, and writes `hospital_cleaned_v2_from_notebook.csv`."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "aaeb6fea",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "pandas 3.0.3\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "from pathlib import Path\n",
    "print('pandas', pd.__version__)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "df7f8a6b",
   "metadata": {},
   "outputs": [],
   "source": [
    "def clean_hospital_data(in_path='hospital_cleaned.csv', out_path='hospital_cleaned_v2_from_notebook.csv'):\n",
    "    import pandas as pd, numpy as np\n",
    "    df = pd.read_csv(in_path)\n",
    "    # drop unnamed columns\n",
    "    df = df.loc[:, ~df.columns.str.contains('^Unnamed', na=False)]\n",
    "    # strip whitespace from object/string columns\n",
    "    for c in df.select_dtypes(include=['object']).columns:\n",
    "        df[c] = df[c].where(df[c].isna(), df[c].str.strip())\n",
    "    # standardize casing for selected text columns\n",
    "    for c in ['Hospital Name','City','State','Department','Doctor','Patient Name','Admission Type','Insurance Provider']:\n",
    "        if c in df.columns:\n",
    "            df[c] = df[c].astype(str).str.title().replace({'Nan': np.nan})\n",
    "    # uppercase ID-like columns\n",
    "    for c in df.columns:\n",
    "        if c.lower().endswith('id') or ' id' in c.lower() or c.lower().startswith('hospital id'):\n",
    "            df[c] = df[c].astype(str).str.upper()\n",
    "    # parse dates\n",
    "    for c in ['Admission Date','Discharge Date']:\n",
    "        if c in df.columns:\n",
    "            df[c] = pd.to_datetime(df[c], errors='coerce')\n",
    "    # parse times to HH:MM strings\n",
    "    for c in ['Admission Time','Discharge Time']:\n",
    "        if c in df.columns:\n",
    "            df[c] = pd.to_datetime(df[c], errors='coerce').dt.strftime('%H:%M').fillna('')\n",
    "    # numeric conversions (best-effort)\n",
    "    for c in ['Age','Beds Available','ICU Beds','Staff Count','Billing Amount','Length of Stay']:\n",
    "        if c in df.columns:\n",
    "            df[c] = pd.to_numeric(df[c], errors='coerce')\n",
    "    # fill missing insurance with 'Self-Pay'\n",
    "    if 'Insurance Provider' in df.columns:\n",
    "        df['Insurance Provider'] = df['Insurance Provider'].replace({'': np.nan}).fillna('Self-Pay')\n",
    "    # fix discharge before admission by setting discharge = admission when earlier\n",
    "    if 'Admission Date' in df.columns and 'Discharge Date' in df.columns:\n",
    "        mask = (df['Discharge Date'].notna()) & (df['Admission Date'].notna()) & (df['Discharge Date'] < df['Admission Date'])\n",
    "        df.loc[mask, 'Discharge Date'] = df.loc[mask, 'Admission Date']\n",
    "    # deduplicate using Patient ID + Admission Date when available\n",
    "    if 'Patient ID' in df.columns and 'Admission Date' in df.columns:\n",
    "        df = df.drop_duplicates(subset=['Patient ID','Admission Date'], keep='first')\n",
    "    # drop fully-empty columns\n",
    "    df = df.dropna(axis=1, how='all')\n",
    "    df.to_csv(out_path, index=False)\n",
    "    print(f'Wrote cleaned file: {out_path}')\n",
    "    return df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "dd196bb8",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "clean_hospital_data.py written\n"
     ]
    }
   ],
   "source": [
    "# Write the same cleaning function to a .py file so it can be reused outside the notebook.\n",
    "pycode = '''\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "def clean_hospital_data(in_path='hospital_cleaned.csv', out_path='hospital_cleaned_v2.csv'):\n",
    "    df = pd.read_csv(in_path)\n",
    "    df = df.loc[:, ~df.columns.str.contains('^Unnamed', na=False)]\n",
    "    for c in df.select_dtypes(include=['object']).columns:\n",
    "        df[c] = df[c].where(df[c].isna(), df[c].str.strip())\n",
    "    for c in ['Hospital Name','City','State','Department','Doctor','Patient Name','Admission Type','Insurance Provider']:\n",
    "        if c in df.columns:\n",
    "            df[c] = df[c].astype(str).str.title().replace({'Nan': np.nan})\n",
    "    for c in df.columns:\n",
    "        if c.lower().endswith('id') or ' id' in c.lower() or c.lower().startswith('hospital id'):\n",
    "            df[c] = df[c].astype(str).str.upper()\n",
    "    for c in ['Admission Date','Discharge Date']:\n",
    "        if c in df.columns:\n",
    "            df[c] = pd.to_datetime(df[c], errors='coerce')\n",
    "    for c in ['Admission Time','Discharge Time']:\n",
    "        if c in df.columns:\n",
    "            df[c] = pd.to_datetime(df[c], errors='coerce').dt.strftime('%H:%M').fillna('')\n",
    "    for c in ['Age','Beds Available','ICU Beds','Staff Count','Billing Amount','Length of Stay']:\n",
    "        if c in df.columns:\n",
    "            df[c] = pd.to_numeric(df[c], errors='coerce')\n",
    "    if 'Insurance Provider' in df.columns:\n",
    "        df['Insurance Provider'] = df['Insurance Provider'].replace({'': np.nan}).fillna('Self-Pay')\n",
    "    if 'Admission Date' in df.columns and 'Discharge Date' in df.columns:\n",
    "        mask = (df['Discharge Date'].notna()) & (df['Admission Date'].notna()) & (df['Discharge Date'] < df['Admission Date'])\n",
    "        df.loc[mask, 'Discharge Date'] = df.loc[mask, 'Admission Date']\n",
    "    if 'Patient ID' in df.columns and 'Admission Date' in df.columns:\n",
    "        df = df.drop_duplicates(subset=['Patient ID','Admission Date'], keep='first')\n",
    "    df = df.dropna(axis=1, how='all')\n",
    "    df.to_csv(out_path, index=False)\n",
    "    print(f'Wrote cleaned file: {out_path}')\n",
    "'''\n",
    "with open('clean_hospital_data.py', 'w', encoding='utf-8') as f:\n",
    "    f.write(pycode)\n",
    "print('clean_hospital_data.py written')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "14b6dbc0",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Chenn\\AppData\\Local\\Temp\\ipykernel_3856\\309380970.py:7: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.\n",
      "See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.\n",
      "  for c in df.select_dtypes(include=['object']).columns:\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Wrote cleaned file: hospital_cleaned_v2_from_notebook.csv\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Hospital ID</th>\n",
       "      <th>Hospital Name</th>\n",
       "      <th>Hospital Type</th>\n",
       "      <th>City</th>\n",
       "      <th>State</th>\n",
       "      <th>Department</th>\n",
       "      <th>Department ID</th>\n",
       "      <th>Doctor</th>\n",
       "      <th>Nurses</th>\n",
       "      <th>Staff Count</th>\n",
       "      <th>...</th>\n",
       "      <th>Beds_Occupied_Count_norm</th>\n",
       "      <th>Equipment_Total_Inventory_norm</th>\n",
       "      <th>Equipment_Usage_Duration_Hours_norm</th>\n",
       "      <th>Number_of_Transfers_norm</th>\n",
       "      <th>Dept_Bed_Capacity_Derived_norm</th>\n",
       "      <th>Dept_ICU_Bed_Capacity_Derived_norm</th>\n",
       "      <th>Dept_Staff_Capacity_Derived_norm</th>\n",
       "      <th>Admissions_Rate_%_Derived_norm</th>\n",
       "      <th>Staff_Utilization_%_Derived_norm</th>\n",
       "      <th>Bed_Occupancy_Rate_%_norm</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>HOSP00016</td>\n",
       "      <td>C K Hospital</td>\n",
       "      <td>Private</td>\n",
       "      <td>Mumbai</td>\n",
       "      <td>Maharashtra</td>\n",
       "      <td>General Medicine</td>\n",
       "      <td>DEPT004</td>\n",
       "      <td>Dr. Arjun Sharma</td>\n",
       "      <td>12</td>\n",
       "      <td>257</td>\n",
       "      <td>...</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.272727</td>\n",
       "      <td>0.728671</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.935484</td>\n",
       "      <td>0.857143</td>\n",
       "      <td>0.956522</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.342561</td>\n",
       "      <td>0.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>HOSP00019</td>\n",
       "      <td>Cure Well Hospital</td>\n",
       "      <td>Private</td>\n",
       "      <td>Bengaluru</td>\n",
       "      <td>Karnataka</td>\n",
       "      <td>General Surgery</td>\n",
       "      <td>DEPT010</td>\n",
       "      <td>Dr. Sneha Rao</td>\n",
       "      <td>15</td>\n",
       "      <td>288</td>\n",
       "      <td>...</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.863636</td>\n",
       "      <td>0.770629</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.661290</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>0.630435</td>\n",
       "      <td>0.333333</td>\n",
       "      <td>0.416378</td>\n",
       "      <td>0.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>HOSP00004</td>\n",
       "      <td>Yashoda Hospital</td>\n",
       "      <td>Private</td>\n",
       "      <td>Hyderabad</td>\n",
       "      <td>Telangana</td>\n",
       "      <td>Pulmonology</td>\n",
       "      <td>DEPT005</td>\n",
       "      <td>Dr. Priya Reddy</td>\n",
       "      <td>20</td>\n",
       "      <td>181</td>\n",
       "      <td>...</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.636364</td>\n",
       "      <td>0.074126</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.919355</td>\n",
       "      <td>0.785714</td>\n",
       "      <td>0.782609</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.200692</td>\n",
       "      <td>0.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>HOSP00017</td>\n",
       "      <td>Dharma Hospital</td>\n",
       "      <td>Private</td>\n",
       "      <td>Delhi</td>\n",
       "      <td>Delhi</td>\n",
       "      <td>Pulmonology</td>\n",
       "      <td>DEPT005</td>\n",
       "      <td>Dr. Rahul Verma</td>\n",
       "      <td>23</td>\n",
       "      <td>170</td>\n",
       "      <td>...</td>\n",
       "      <td>0.166667</td>\n",
       "      <td>0.454545</td>\n",
       "      <td>0.358042</td>\n",
       "      <td>0.333333</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>0.928571</td>\n",
       "      <td>0.934783</td>\n",
       "      <td>0.333333</td>\n",
       "      <td>0.175317</td>\n",
       "      <td>0.166667</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>HOSP00017</td>\n",
       "      <td>Dharma Hospital</td>\n",
       "      <td>Private</td>\n",
       "      <td>Delhi</td>\n",
       "      <td>Delhi</td>\n",
       "      <td>Icu</td>\n",
       "      <td>DEPT009</td>\n",
       "      <td>Dr. Priya Reddy</td>\n",
       "      <td>34</td>\n",
       "      <td>116</td>\n",
       "      <td>...</td>\n",
       "      <td>0.333333</td>\n",
       "      <td>0.318182</td>\n",
       "      <td>0.116084</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.919355</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>0.478261</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.078431</td>\n",
       "      <td>0.333333</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>5 rows × 77 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "  Hospital ID       Hospital Name Hospital Type       City        State  \\\n",
       "0   HOSP00016        C K Hospital       Private     Mumbai  Maharashtra   \n",
       "1   HOSP00019  Cure Well Hospital       Private  Bengaluru    Karnataka   \n",
       "2   HOSP00004    Yashoda Hospital       Private  Hyderabad    Telangana   \n",
       "3   HOSP00017     Dharma Hospital       Private      Delhi        Delhi   \n",
       "4   HOSP00017     Dharma Hospital       Private      Delhi        Delhi   \n",
       "\n",
       "         Department Department ID            Doctor  Nurses  Staff Count  ...  \\\n",
       "0  General Medicine       DEPT004  Dr. Arjun Sharma      12          257  ...   \n",
       "1   General Surgery       DEPT010     Dr. Sneha Rao      15          288  ...   \n",
       "2       Pulmonology       DEPT005   Dr. Priya Reddy      20          181  ...   \n",
       "3       Pulmonology       DEPT005   Dr. Rahul Verma      23          170  ...   \n",
       "4               Icu       DEPT009   Dr. Priya Reddy      34          116  ...   \n",
       "\n",
       "  Beds_Occupied_Count_norm Equipment_Total_Inventory_norm  \\\n",
       "0                 0.000000                       0.272727   \n",
       "1                 0.000000                       0.863636   \n",
       "2                 0.000000                       0.636364   \n",
       "3                 0.166667                       0.454545   \n",
       "4                 0.333333                       0.318182   \n",
       "\n",
       "  Equipment_Usage_Duration_Hours_norm  Number_of_Transfers_norm  \\\n",
       "0                            0.728671                  0.000000   \n",
       "1                            0.770629                  0.000000   \n",
       "2                            0.074126                  0.000000   \n",
       "3                            0.358042                  0.333333   \n",
       "4                            0.116084                  0.000000   \n",
       "\n",
       "  Dept_Bed_Capacity_Derived_norm Dept_ICU_Bed_Capacity_Derived_norm  \\\n",
       "0                       0.935484                           0.857143   \n",
       "1                       0.661290                           1.000000   \n",
       "2                       0.919355                           0.785714   \n",
       "3                       1.000000                           0.928571   \n",
       "4                       0.919355                           1.000000   \n",
       "\n",
       "  Dept_Staff_Capacity_Derived_norm Admissions_Rate_%_Derived_norm  \\\n",
       "0                         0.956522                       0.000000   \n",
       "1                         0.630435                       0.333333   \n",
       "2                         0.782609                       0.000000   \n",
       "3                         0.934783                       0.333333   \n",
       "4                         0.478261                       0.000000   \n",
       "\n",
       "  Staff_Utilization_%_Derived_norm Bed_Occupancy_Rate_%_norm  \n",
       "0                         0.342561                  0.000000  \n",
       "1                         0.416378                  0.000000  \n",
       "2                         0.200692                  0.000000  \n",
       "3                         0.175317                  0.166667  \n",
       "4                         0.078431                  0.333333  \n",
       "\n",
       "[5 rows x 77 columns]"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Run the cleaning function on the provided CSV and show a sample\n",
    "out_df = clean_hospital_data(in_path='hospital_cleaned.csv', out_path='hospital_cleaned_v2_from_notebook.csv')\n",
    "out_df.head()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
